//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public Client()
        {
            this.Bookings = new HashSet<Booking>();
            this.Packages = new HashSet<Package>();
        }
    
        public int clientid { get; set; }
        [Required]
        public string clientname { get; set; }
        public string password { get; set; }
        [Required]
        [EmailAddress (ErrorMessage ="Email address is not correct")]
        public string clientemail { get; set; }
        [Required]
        [StringLength (11)]
        public string mobileno { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
    }
}
